### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by paul321** [ibericode/vat#15]
The library is crashing because https://jsonvat.com has an expired certificate.
Please change https://jsonvat.com/ to http://jsonvat.com/ by removing the https or add a rule to curl to accept invalid certificate.

**Comment by digilist** [comment]
The issue was fixed, see adamcooke/vat-rates#35

I do not think that disabling SSL or accepting invalid certificates is a proper solution! I think having a local adapter (see #2) would be much better that can handle the requests in case of a failure or something.

**Comment by paul321** [comment]
Hi,
What do you mean by (see #2) ?

**Comment by digilist** [comment]
That you have an adapter that fetches stores the data locally that can be used as data source (or fallback)

**Comment by paul321** [comment]
Can you link an example or a commit?
Thanks!

**Comment by digilist** [comment]
There is no example or commit yet, it is an open issue.

**Comment by paul321** [comment]
Oh ok, i though there is already a solution, it's not a good experience for the users when they want to pay and the service crashes because a certificate. :)

**Comment by kachar** [comment]
Certificate of https://jsonvat.com/ has expired again today..

**Comment by dannyvankooten** [comment]
Hey everyone,

These errors were due to jsonvat.com experiencing issues, so outside of our control. To ensure this never happens again I made some modifications for version 2.0 of this package.

- VAT rates are now fetched from [ibericode/vat-rates](https://github.com/ibericode/vat-rates)  directly, so we can benefit from GitHub's infra.
- Rates are stored in a local file which is periodically refreshed. When the chosen VAT rates service is down, the package will use the local file as a fallback until issues are resolved.
