### ISSUE TITLE
RegEx for Northern Ireland (XI)

### ISSUE THREAD

**Issue by KaHa6uc** [ibericode/vat#42]
As desribed at https://ec.europa.eu/taxation_customs/vies/faqvies.do#item_11 : 
```
'XI' => '(GD\d{3}|HA\d{3}|\d{9}|\d{12})'
```

**Comment by dannyvankooten** [comment]
This library only allows for validation of VAT numbers which are EU member states, which Northern Ireland is not. Correct me if I'm wrong please.

**Comment by lowerends** [comment]
Hi,

I think Northern Ireland is a special case, since in practice it is considered EU for VAT and tax related issues. Moreover the VIES database allows to lookup VAT numbers for Northern Ireland: [https://ec.europa.eu/taxation_customs/vies/#/vat-validation](https://ec.europa.eu/taxation_customs/vies/#/vat-validation).
So, basically, all that this would required is adding XI indeed to the list of countries in the Validator file as @KaHa6uc describes.

Any change this gets revisited?

Thanks!
